### ISSUE TITLE
Python 科學計算快速入門 1/2

### ISSUE THREAD

**Issue by Superdanby** [amoshyc/blog#1]
#management
~~a = b: 讓變數名稱 a 指向「變數名稱 b 所指的物件」~~
b = a: 讓變數名稱 b 指向「變數名稱 a 所指的物件」
這樣跟底下的圖比較符合,  才不會誤導讀者(?

#frequently-used-patterns
print(range(3)) # ~~[0, 1, 2]~~ range(0, 3)

**Comment by amoshyc** [comment]
Fixed
